name: Unit Tests
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu, macos]
        os: [ubuntu]
        # ruby: [2.3, 2.4, 2.5, 2.6, 2.7, head, jruby, jruby-head, truffleruby, truffleruby-head, rubinius]
        ruby: [2.4, head, jruby, truffleruby]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
          bundle config set without 'integrations extras'
          bundle install --jobs 4 --retry 2
          bundle exec rspec spec/*.rb
