name: Tests
on: [push]
jobs:
  test-container:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=12s
          --health-timeout=6s
          --health-retries=6
    steps:
    - name: Setup MySQL
      env:
        MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
      run: |
        apt-get update
        apt-get install -y mysql-client
        mysql --host mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS command_search_db_test;'
        mysql --host mysql -uroot -e "SHOW DATABASES"
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Apt Install
      run: apt-get install -yqq libpq-dev rubygems ruby ruby-dev rubygems-integration libsqlite3-dev
    - name: Bundle
      run: |
        ruby -v
        gem install bundler
        bundle install --jobs=4 --retry=2
    # - name: Rspec
    #   run: bundle exec rspec
      # env:
      #   MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}







# name: Test
# on:
#   push:
#     branches: [ master ]
#   pull_request:
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     services:
#       mysql:
#         image: mysql:5.7
#         env:
#           MYSQL_DATABASE: command_search_db_test
#           MYSQL_ROOT_PASSWORD: root
#           MYSQL_USER: root
#           # MYSQL_HOST: 127.0.0.1
#           # MYSQL_ALLOW_EMPTY_PASSWORD: true
#           # MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
#         ports:
#         - 3306
#         options: >-
#           --health-cmd="mysqladmin ping"
#           --health-interval=8s
#           --health-timeout=4s
#           --health-retries=2
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_HOST_AUTH_METHOD: trust
#           POSTGRES_USER: command_search_user_test
#           POSTGRES_DB: command_search_db_test
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 8s
#           --health-timeout 4s
#           --health-retries 2
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup Ruby
#       uses: actions/setup-ruby@v1
#       with:
#         ruby-version: 2.7.1
#     - name: Apt Install
#       run: sudo apt-get install -y -qq build-essential gnupg2 procps default-libmysqlclient-dev libsqlite3-dev
#     - name: Setup Mysql
#       run: |
#         mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS command_search_db_test;'
#     - name: Bundle
#       run: |
#         gem install bundler -v 2.1.4
#         bundle install --jobs=4 --retry=2
#     - name: Rspec
#       run: bundle exec rspec
#       env:
#         MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
