name: Unit Tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu, macos]
        os: [ubuntu]
        # ruby: [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, head, jruby, jruby-head, truffleruby, truffleruby-head, rubinius]
        ruby: [2.1, head, jruby, truffleruby, rubinius]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
          gem install bundler -v 2.0.2
          gem update --system
          bundle update --bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 2
          bundle exec rspec spec/*.rb
