name: Rails Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Test
        run: |
          echo "yoyoyo"




# name: Test
# on:
#   push:
#     branches: [ master ]
#   pull_request:
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     services:
#       mysql:
#         image: mysql:5.7
#         env:
#           MYSQL_DATABASE: command_search_db_test
#           MYSQL_ROOT_PASSWORD: root
#           MYSQL_USER: root
#           # MYSQL_HOST: 127.0.0.1
#           # MYSQL_ALLOW_EMPTY_PASSWORD: true
#           # MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
#         ports:
#         - 3306
#         options: >-
#           --health-cmd="mysqladmin ping"
#           --health-interval=8s
#           --health-timeout=4s
#           --health-retries=2
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_HOST_AUTH_METHOD: trust
#           POSTGRES_USER: command_search_user_test
#           POSTGRES_DB: command_search_db_test
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 8s
#           --health-timeout 4s
#           --health-retries 2
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup Ruby
#       uses: actions/setup-ruby@v1
#       with:
#         ruby-version: 2.7.1
#     - name: Apt Install
#       run: sudo apt-get install -y -qq build-essential gnupg2 procps default-libmysqlclient-dev libsqlite3-dev
#     - name: Setup Mysql
#       run: |
#         mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS command_search_db_test;'
#     - name: Bundle
#       run: |
#         gem install bundler -v 2.1.4
#         bundle install --jobs=4 --retry=2
#     - name: Rspec
#       run: bundle exec rspec
#       env:
#         MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
